packages:
  - server
  - client

allowBuilds:
  "@prisma/engines": false
  esbuild: false
  isolated-vm: true
  msw: false
  prisma: false
  protobufjs: true

minimumReleaseAgeExclude:
  - '@yukino.js/sentry@0.0.1 || 0.0.7'
  - '@yukino.js/yukino@0.0.1 || 0.0.22 || 0.0.24 || 0.0.36 || 0.0.37'
